steps:
  # Сборка Docker образа
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-app:$COMMIT_SHA', '.']

  # Загрузка Docker образа в Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/my-app:$COMMIT_SHA']

  # Получение учетных данных кластера Kubernetes и развертывание
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      gcloud container clusters get-credentials cluster-shmaster --zone europe-west1 --project $PROJECT_ID && \
      kubectl apply -f kubernetes.yaml

images:
  - 'gcr.io/$PROJECT_ID/my-app:$COMMIT_SHA'
