steps:
  # Шаг 1: Сборка Docker образа из Докерфайла
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-app:$SHORT_SHA', '.']

  # Шаг 2: Загрузка собранного образа в Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/my-app:$SHORT_SHA']

images:
  - 'gcr.io/$PROJECT_ID/my-app:$SHORT_SHA'