steps:
  # Сборка Docker образа
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-app:$COMMIT_SHA', '.']

  # Загрузка Docker образа в Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/my-app:$COMMIT_SHA']

  # Установка kubectl (если это еще не сделано)
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['version']

  # Получение учетных данных кластера Kubernetes
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['container', 'clusters', 'get-credentials', 'cluster-shmaster', '--zone', 'europe-west1', '--project', '$PROJECT_ID']

  # Развертывание в Kubernetes
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'kubernetes.yaml']

images:
  - 'gcr.io/$PROJECT_ID/my-app:$COMMIT_SHA'