steps:
  # Сборка Docker образа
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-app:$COMMIT_SHA', '.']

  # Загрузка Docker образа в Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/my-app:$COMMIT_SHA']

  # Установка kubectl (если это еще не сделано)
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['version']

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      gcloud container clusters get-credentials cluster-shmaster \
        --zone $CLOUDSDK_COMPUTE_ZONE \
        --project $PROJECT_ID
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=europe-west1'
    - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-shmaster'
    - 'KUBECTL_VERSION=1.21'

  # Развертывание в Kubernetes
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'kubernetes.yaml']

images:
  - 'gcr.io/$PROJECT_ID/my-app:$COMMIT_SHA'